module gy91_init_tb (
  input logic clk,
  input logic rst_n,
  input logic reinitialize,
  output logic reinitialize_ready,
  input logic scl_i,
  input logic sda_i,
  output logic scl_drive_low,
  output logic sda_drive_low,
  output logic initializing, ready, failed,
  output logic mpu_present, mpu_ready, mpu_failed,
  output logic ak_present, ak_ready, ak_failed,
  output logic bmp_present, bmp_ready, bmp_failed,
  output logic [6:0] mpu_address, bmp_address,
  output logic [23:0] ak_asa,
  output logic [191:0] bmp_calibration,
  output logic [15:0] mpu_error_count, ak_error_count, bmp_error_count,
  output logic [3:0] last_i2c_error,
  output logic [1:0] last_failed_device,
  output logic [7:0] last_failed_step,
  output logic [15:0] init_sequence,
  output logic monitor_cmd_accepted,
  output logic [6:0] monitor_cmd_address,
  output logic [7:0] monitor_cmd_write_count,
  output logic [7:0] monitor_cmd_read_count,
  output logic monitor_cmd_fast_mode
);
  gy91_init_subsystem #(
    .POWER_UP_CYCLES(5),
    .MPU_RESET_CYCLES(6),
    .MPU_WAKE_CYCLES(5),
    .AK_MODE_CYCLES(3),
    .BMP_POLL_INTERVAL_CYCLES(4),
    .BMP_POLL_LIMIT(4),
    .RETRY_DELAY_CYCLES(3),
    .MAX_TRANSACTION_RETRIES(2),
    .I2C_LOW_CYCLES(3),
    .I2C_HIGH_CYCLES(3),
    .I2C_BUS_FREE_CYCLES(3),
    .I2C_STRETCH_TIMEOUT(30),
    .I2C_TRANSACTION_TIMEOUT(10000)
  ) dut (.*);
endmodule
